### PR TITLE
Attempt deploy 5 times before giving up

### PR DESCRIPTION
**Pull request by forabi**
Also, move the deployment command to a separate shell file to simplify the Dockerfile.

### CODE REVIEW

**Comment by forabi** [comment]
@msafih should I rewrite this in JS too?

**Comment by wholesomedev** [comment]
Yeah, as we discussed, we need to have our scripts in JS.

**Comment by forabi** [comment]
Rebased on master and rewritten in JS

**Review by wholesomedev — APPROVED** [review]
LGTM

**Pull request merged**
