### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by forabi**
This is still work in progress, and I would like to know what else should be included in the README or if anything can be improved.

### CODE REVIEW

**Comment by wholesomedev** [comment]
Is there a relation between this Docker file and the one in the main repo? If so, maybe that relationship can be documented? Otherwise, this LGTM

**Review by wholesomedev — APPROVED** [review]
LGTM

**Comment by forabi** [comment]
> Is there a relation between this Docker file and the one in the main repo?

No. This image is used in Travis to install the `gcloud` command line tool which is used to push the code to App Engine. The Dockerfile in the main repo is used to define the custom runtime we use to _run_ the app in App Engine. We could remove the Dockerfile in the main repo and use any other App Engine runtime (not just the Docker-based runtime) and nothing has to change in this repo.

**Comment by wholesomedev** [comment]
Sounds good 👍

**Pull request merged**
